language: cpp
os:
  - linux

sudo: required
dist: trusty
notifications: 
  email: false

git:
  submodules: false

services: 
  - docker

matrix:
  include:
    - os: linux
      before_install: 
        - sudo docker pull onnc/ubuntu-14.04-llvm
        - sudo docker create --privileged=true -t --name container onnc/ubuntu-14.04-llvm
        - sudo docker start container

      script: 
        - sudo docker exec -t container /bin/bash -c "mkdir onnc/build"
        - sudo docker exec -t container /bin/bash -c "cd onnc/build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install .."
        - sudo docker exec -t container /bin/bash -c "cd onnc/build && make -j12 install"